# Generated by Django 3.0 on 2021-07-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
